### ISSUE TITLE
Implement ForceField Algorithm

### ISSUE THREAD

**Issue by nahueltaibo** [nahueltaibo/netcorerover#10]
To be able to navigate autonomously, we should implement the **Force Field algorithm** . Responsible of creating a resulting force for the robot to move to, composed of adding forces of detected obstacles and RC input.

![image](https://user-images.githubusercontent.com/6831744/75816474-493b7400-5d63-11ea-90b3-980877e21aa4.png)

[Check this link for a description about it](https://www.sciencedirect.com/science/article/pii/S2214914718305130#cap0040)

**Comment by turboslon** [comment]
#9 has to be implemented first. Without sensor data, it's difficult to determine obstacles 😊

**Comment by turboslon** [comment]
I'd like to share/discuss the implementation details below, as long as the #9 issue is still on its way to develop branch.
As we don't have an actual target (we've got only requested velocity vector), we cannot predict a path for a robot to reach the target. The only thing we can do is to change the resulting vector accordingly. So I'll do these changes:

1. RemoteControlAgent will raise not the VelocityMessage but something like PlannedVelocityMessage.
1. After that AFP algorithm (please refer to the "Artificial potential field (APF) approach" in the article @nahueltaibo provided) comes along and revises the velocity vector considering the obstacles it senses.
1. After calculations, AFP algorithm raises the VelocityMessage with corrected velocity vector that will be propagated to the DCMotorDriver

**Comment by turboslon** [comment]
I'm almost done with it. I hope will do a PR today. There are just a few issues left.

**Comment by turboslon** [comment]
Resolved with #23
