### ISSUE TITLE
Cannot pull the nuget packages

### ISSUE THREAD

**Issue by turboslon** [nahueltaibo/netcorerover#13]
I'm sure that it's just my github account issue, but I cannot figure out, how to pull the nuget packages from a github nuget server. 
Visual studio asks me for a login / password to nuget.pkg.github.com. And my personal username / password don't work:
`Error occurred while restoring NuGet packages: Failed to retrieve information about 'Iot.Device.Bindings' from remote source 'https://nuget.pkg.github.com/nahueltaibo/download/iot.device.bindings/index.json'.`
And when I try to build project, I receive a lot of:
`...\NetCoreRover\src\Robot.Start\Robot.Start.csproj : warning Undefined: Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:packages'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.`
However, I can build a solution, run and debug it...

Could someone (Nahuel? 😁) guide me please?

**Comment by nahueltaibo** [comment]
@turboslon  I just pushed to develop a change removing the Github packages source from NuGet.Config.. that might be related with your issue.

Also please check that you have in the solution folder a NuGet.Config with the following nuget sources:

	<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />    
	<add key="DotNet IoT" value="https://dotnetfeed.blob.core.windows.net/dotnet-iot/index.json" />

We need them as some stuff (like the MotorHat )is not in nuget.org yet

**Comment by nahueltaibo** [comment]
Now that its not just me coding this Ill need to stop pushing straight to develop, sorry for that :)

**Comment by nahueltaibo** [comment]
You can also check if you have the prerelease checkbox set in the solution nuget package manager
And Package source: All (instead of nuget.org)

**Comment by nahueltaibo** [comment]
I spent like 4 hours fighting with packages... I hope I solved the issue in both robots...
Spot uses the same projects we have in NetCoreRover, but gets them from nuget.org
Check if it works and let me know if it does not

**Comment by turboslon** [comment]
Thanks for the changes you made. Now it's fine
