### ISSUE TITLE
Implement DistanseSensor code for the HC-SR04 sonar sensor

### ISSUE THREAD

**Issue by nahueltaibo** [nahueltaibo/netcorerover#9]
The robot has 3  **HC-SR04** sonar sensors in its front. This story is about creating the required infrastructure to publish to the MessageBus the readings from these sensors.

### Technical notes
Probably at least all these needs to be implemented:
- [x] IDistanceSensor driver interface
- [x] HcSr04DistanceSensorDriver implementation of IDistanceSensor
- [x] IDistanceSensorController: IHostedService
- [x] DistanceSensorController : IDistanceSensorController
- [x] DistanceMessage : IMessage

**Comment by turboslon** [comment]
I will implement initial
